spring:
  profiles:
    active:
    - dev
---
server:
  port: 7001
spring:
  profiles: dev       
  application:
    name: microservicecloud-eureka-client
eureka:
  instance:
    hostname: eureka7001   #eureka服务端的实例名称
  client:  
    register-with-eureka: false     #false表示不向注册中心注册自己    
    fetch-registry: false   #false表示自己是注册中心，职责就是维护服务实例，并不需要去检索服务    
    service-url:    
      defaultZone: http://eureka7001:7001/eureka/
---
server:
  port: 7001
spring:
  profiles: test     
  application:
    name: microservicecloud-config-client
eureka:
  instance:
    hostname: eureka7001   #eureka服务端的实例名称
  client:  
    register-with-eureka: false     #false表示不向注册中心注册自己    
    fetch-registry: false   #false表示自己是注册中心，职责就是维护服务实例，并不需要去检索服务    
    service-url:    
      defaultZone: http://eureka7001:7001/eureka/